CONNECT EPM_SERVICE PASSWORD Abcd1234
;;
drop PROCEDURE "SAP_FPA_SERVICES"."ABC"
;;
create PROCEDURE "SAP_FPA_SERVICES"."ABC"
(OUT OUT_FILTER NVARCHAR(5000)) LANGUAGE SQLSCRIPT SQL SECURITY DEFINER READS SQL DATA AS
  BEGIN
OUT_FILTER := '"ID" >= ''''';
END
;;
grant execute on "SAP_FPA_SERVICES"."ABC" to _SYS_REPO
;;
drop STRUCTURED PRIVILEGE "EE_ABC"
;;
create STRUCTURED PRIVILEGE "EE_ABC" FOR SELECT ON "_SYS_BIC"."test.infra/PERSON_CALC","_SYS_BIC"."test.infra/PERSON_CALC/olap" condition provider "SAP_FPA_SERVICES"."ABC"
;;